# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e3a35f6a76d9b12e9958809a0ca41ad29f2df028efb495f38d29f61b443c10965ffdb6ee0c85871fa9b1fe9f8d90f0aa581ffba282d771236916d4c7b4938b8

test:
  secret_key_base: 2287f9d68f6bc16bc04fe493e43f80c8ac17cc36933c4812624e7c7e6345859cb0356b8c523fc2735c01f4a2dd7f8f4ce08a14f867e30a1972d4c6f8ace7f614

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
