# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e01c6ee5e14763f28052d37b13dd2d007e94f1bdf224bffd0a3a75d534e21a1e6596452e06148b21124eeb2f7a696fea058cb2f7c533d880ad1ec7e8d41f4d64

test:
  secret_key_base: 0693f6bb44058b946c652a503b3ae29e497183c98ea1be2c7d37135711679c4d7f37d8fd0f49bf624a1a1214de017c04e34b6a8e3428f3fa1453c4e3aa19d8e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
